name: tbloc_dart
version: 0.3.0
description: A dart library that helps you to implement the BLoC pattern.
homepage: https://github.com/tyrcord/tbloc_dart
issue_tracker: https://github.com/tyrcord/tbloc_dart/issues
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  async: ^2.4.1
  rxdart: ^0.24.1
  equatable: ^1.2.0
  subx: ^0.5.0
  provider: ^4.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1
  test: ^1.9.4
