name: tbloc_dart
version: 0.17.1
description: A dart library that helps you to implement the BLoC pattern.
homepage: https://github.com/tyrcord/tbloc_dart
issue_tracker: https://github.com/tyrcord/tbloc_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  async: ^2.6.1
  rxdart: ^0.27.1
  subx: ^1.0.3
  provider: ^5.0.0
  logger: ^1.0.0
  tuple: ^2.0.0
  tmodel_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  dart_code_metrics: ^4.0.1
