name: tbloc_dart
version: 0.14.1
description: A dart library that helps you to implement the BLoC pattern.
homepage: https://github.com/tyrcord/tbloc_dart
issue_tracker: https://github.com/tyrcord/tbloc_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  async: ^2.5.0
  rxdart: ^0.26.0
  equatable: ^2.0.0
  subx: ^1.0.0
  provider: ^5.0.0
  logger: ^1.0.0
  tuple: ^2.0.0
  tmodel_dart: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
  # dart_code_metrics: ^2.4.0
