name: tbloc_dart
version: 0.12.0
description: A dart library that helps you to implement the BLoC pattern.
homepage: https://github.com/tyrcord/tbloc_dart
issue_tracker: https://github.com/tyrcord/tbloc_dart/issues

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3
  async: ^2.4.2
  rxdart: ^0.24.1
  equatable: ^1.2.5
  subx: ^0.6.1
  provider: ^4.3.2+2
  logger: ^0.9.4
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.15.4
